require("js/egret.min.js")
require("js/game.min.js")
require("js/tween.min.js")
require("js/assetsmanager.min.js")
require("js/socket.min.js")
require("js/particle.min.js")
require("js/physics.min.js")
require("js/main.min.js")